version: '3.7'
services:
  mon:
    image: ceph/daemon:latest-nautilus-devel
    container_name: mon
    command: mon
    environment:
      - MON_IP=172.21.32.104,172.21.32.106,172.21.32.110
      - CEPH_PUBLIC_NETWORK=172.21.32.0/24
      - CEPH_CLUSTER_NETWORK=172.21.32.0/24
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    deploy:
      replicas: 1
    networks:
      - hostnet
      
  rgw:
    image: ceph/daemon:latest-nautilus-devel
    container_name: rgw
    command: rgw
    restart: always
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    depends_on:
      - mon
    deploy:
      replicas: 1
    networks:
      - hostnet 
      
  osd:
    image: ceph/daemon:latest-nautilus-devel
    container_name: osd
    command: osd
    restart: always
    privileged: true
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /dev:/dev
      - /opt/ceph/rbd:/var/lib/ceph/osd
      - /var/log/ceph/:/var/log/ceph
    depends_on:
      - mon
    deploy:
      replicas: 1
    networks:
      - hostnet 
      
  mgr:
    image: ceph/daemon:latest-nautilus-devel
    container_name: mgr
    command: mgr
    restart: always
    volumes:
      - /etc/ceph:/etc/ceph
      - /var/lib/ceph:/var/lib/ceph
      - /var/log/ceph/:/var/log/ceph
    depends_on:
      - mon
    deploy:
      replicas: 1
    networks:
      - hostnet 
 
  mysql:
    image: 172.21.32.31:5000/mysql-canal:5.7.22
    container_name: mysql
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
    volumes:
      - /home/deploy/config/mysql/data:/var/lib/mysql
      - /home/deploy/config/mysql/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3306:3306
    deploy:
      replicas: 2

  mysql3307:
    image: 172.21.32.31:5000/mysql:5.7.22
    container_name: mysql3307
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlPwd1@
    volumes:
      - /home/deploy/config/mysql3307/data:/var/lib/mysql
      - /home/deploy/config/mysql3307/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3307:3306
    deploy:
      replicas: 2

networks:
   hostnet:
      external: true
      name: host
   ingress:
     driver: overlay
     attachable: true
   nonet:
     external: true
     name: none
