version: '3.7'
services:
   portainer:
      image: 172.21.32.102:5000/portainer/portainer:1.24.0
      command: -H unix:///var/run/docker.sock
      restart: always
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
      ports:
      - 9000:9000
      - 18000:8000
      deploy:
         replicas: 1
   