version: '3.7'
services:
   registry:
      image: registry:2.7.1
      environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      volumes:
      - /opt/central/registry:/var/lib/registry
      - /opt/central/registry/config.yml:/etc/docker/registry/config.yml
      ports:
      - 5000:5000
      deploy:
         replicas: 1
   registry-ui:
      image: joxit/docker-registry-ui:1.4
      environment:
#      - PULL_URL=http://172.21.32.102:5000
      - URL=http://172.21.32.102:5000
#      - REGISTRY_URL=http://172.21.32.102:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE="Docker Registry"
      ports:
      - 15000:80
      deploy:
         replicas: 1
   registry-ui2:
      image: jc21/registry-ui:2.0.2
      environment:
      - NODE_ENV=production
      - REGISTRY_DOMAIN=172.21.32.102:5000
      - REGISTRY_HOST=172.21.32.102:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_SSL=false
      ports:
      - 25000:80
      deploy:
         replicas: 1