version: '3.8'
volumes:
  portaince:
    external: true
services:
  portainer_agent:
    image: 172.21.32.31:5000/portainer/agent:2.6.0
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    # - /:/host
    networks:
      - swarm_network
    ports:
      - 9001:9001
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux] 
  portainer:
    image: 172.21.32.31:5000/portainer/portainer-ce:2.6.0
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    networks:
      - swarm_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #	- /opt/portainer:/data
      - portaince:/data
    ports:
      - 9000:9000
    deploy:
        mode: replicated
        replicas: 1
        placement:
            constraints: [node.role == manager]

networks:
  swarm_network:
    driver: overlay
    attachable: true