version: '3.7'
services:
   nginx:
      image: 172.21.32.102:5000/nginx:1.17.4
      restart: always
      environment:
      - PKG_RELEASE=1
      volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 8000:80
      deploy:
         replicas: 1
         
   nginx2:
      image: 172.21.32.102:5000/nginx:1.17.4
      restart: always
      environment:
      - PKG_RELEASE=1
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      configs:
      - source: nginx2.conf
        target: /etc/nginx/nginx.conf
        mode: 777
      ports:
      - 7000:80
      deploy:
         replicas: 1
         
   nginx3:
      image: 172.21.32.102:5000/nginx:1.17.4
      restart: always
      environment:
      - PKG_RELEASE=1
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      configs:
      - source: nginx3.conf
        target: /etc/nginx/nginx.conf
        mode: 777
      ports:
      - 6000:80
      deploy:
         replicas: 1
 
configs:
  nginx.conf:
    file: /opt/nginx/nginx.conf
  nginx2.conf:
    external: true
  nginx3.conf:
    external: true
   