version: '3.7'
services: 
   mysql:
      image: 172.21.32.102:5000/mysql-canal:5.7.28
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=root
      volumes:
      - /opt/deploy/data/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 13306:3306
      deploy:
         replicas: 1
   sonarqube:
      image: 172.21.32.102:5000/sonarqube:7.8-community
      environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
      - SONARQUBE_JDBC_URL=jdbc:mysql://172.21.32.102:13306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      volumes:
      - /opt/sonarqube/sonarqube7.8/conf:/opt/sonarqube/conf
      #- /opt/sonarqube/sonarqube7.8/data:/opt/sonarqube/data
      - /opt/sonarqube/sonarqube7.8/extensions/plugins:/opt/sonarqube/extensions/plugins
      #- /opt/sonarqube/sonarqube7.8:/opt/sonarqube
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 9999:9000
      - 9992:9092
      deploy:
         replicas: 1