version: '3.7'
services:
   registry:
      image: registry:latest
      environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      volumes:
      - /opt/registry:/var/lib/registry
      - /opt/registry/config.yml:/etc/docker/registry/config.yml
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 5000:5000
      deploy:
         replicas: 1
   registry-ui:
      image: joxit/docker-registry-ui:1.5
      environment:
#      - PULL_URL=http://172.21.44.32:5000
      - REGISTRY_URL=http://172.21.44.32:5000
#      - NGINX_PROXY_PASS_URL=http://172.21.44.32:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - CATALOG_ELEMENTS_LIMIT=100000
      - REGISTRY_TITLE="DockerË½¿âÖÐÐÄ"
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 15000:80
      deploy:
         replicas: 1
   registry-ui2:
      image: jc21/registry-ui:2.0.2
      environment:
      - NODE_ENV=production
      - REGISTRY_DOMAIN=172.21.44.32:5000
      - REGISTRY_HOST=172.21.44.32:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_SSL=false
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 25000:80
      deploy:
         replicas: 1
   nexus3:
      image: sonatype/nexus3:3.24.0
      environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      volumes:
      - /opt/central/nexus/nexus3/data:/nexus-data
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 8000:8081
      deploy:
         replicas: 1