version: '3.7'
services:
##############################################################################################
####################################### data Service##########################################
##############################################################################################
   zookeeper:
      image: 172.21.32.102:5000/zookeeper:3.5.8
      restart: always
      environment:
         ZOO_TICK_TIME: 10000
         ZOO_INIT_LIMIT: 6
         ZOO_SYNC_LIMIT: 6
         ZOO_MAX_CLIENT_CNXNS: 100
         ZOO_STANDALONE_ENABLED: 'true'
         ZOO_ADMINSERVER_ENABLED: 'true'
         ZOO_AUTOPURGE_PURGEINTERVAL: 0
         ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
         ZOO_4LW_COMMANDS_WHITELIST: srvr
      volumes:
      #- /opt/deploy/data/zookeeper/data:/data
      #- /opt/deploy/data/zookeeper/datalog:/datalog
      #- /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 2181:2181
      - 28081:8080
      deploy:
         replicas: 1 
   kafka:
      image: 172.21.32.102:5000/wurstmeister/kafka:2.12-2.5.0
      restart: always
      environment:
         BROKER_ID_COMMAND: "echo 102"
         HOSTNAME_COMMAND: "ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v 0.0.0.0|grep -v inet6|grep 10.0|awk '{print $$2}'|tr -d 'addr:'"
         KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:19092,OUTSIDE://172.21.32.102:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
         KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10
         KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 60000
         KAFKA_ZOOKEEPER_SYNC_TIME_MS: 60000
         KAFKA_LOG_DIRS: "/kafka/data"
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
         KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 60000
         KAFKA_SOCKET_SEND_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
         KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
         KAFKA_QUOTA_PRODUCER_DEFAULT: 104857600
         KAFKA_QUOTA_CONSUMER_DEFAULT: 104857600
         KAFKA_DEFAULT_REPLICATION_FACTOR: 1
         KAFKA_OFFSETS_REPLICATION_FACTOR: 1
         KAFKA_NUM_PARTITIONS: 1
      volumes:
      # - /opt/deploy/data/kafka/conf/server.properties:/opt/kafka/config/server.properties
      #- /opt/deploy/data/kafka/data:/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
       - target: 9092
         published: 9092
         protocol: tcp
         mode: host
      deploy:
         replicas: 1
   kafka-manager:
      image: 172.21.32.102:5000/kafkamanager/kafka-manager:3.0.0.4
      restart: always
      environment:
         ZK_HOSTS: 172.21.32.102:2181
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 19000:9000
      deploy:
         replicas: 1
   cerebro:
      image: 172.21.32.102:5000/lmenezes/cerebro:0.8.5
      restart: always
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 9001:9000
      deploy:
         replicas: 1
   mqtt-broker:
      image: 172.21.32.102:5000/eclipse-mosquitto:1.6.10
      restart: always
      volumes:
      - /opt/deploy/data/mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/deploy/data/mosquitto/conf/pwfile.conf:/mosquitto/config/pwfile.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 1883:1883
      deploy:
         replicas: 1